openapi: 3.2.0
info:
  contact:
    email: bruce.sun@itering.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a subscan API server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Subscan Nomination Pools API
  version: '1.0'
servers:
- url: https://https://www.subscan.io/
tags:
- name: NominationPools
paths:
  /api/scan/nomination_pool/activities:
    post:
      description: This API only supports networks with nominationPools frame
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {}
      summary: Nomination Pools Activities
      tags:
      - NominationPools
      x-synonyms:
      - nomination
      - pools
      - activities
      - nominationpools
      - scan
      - pool
      - staking pool
      - delegation
      - nomination pool
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_pluginv2_pallets_nominationPool.nominationPoolsActivitiesParams'
        description: params
        required: true
  /api/scan/nomination_pool/pool:
    post:
      description: This API only supports networks with nominationPools frame
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {}
      summary: Nomination Pools Info
      tags:
      - NominationPools
      x-synonyms:
      - nomination
      - pools
      - nominationpools
      - scan
      - pool
      - staking pool
      - delegation
      - nomination pool
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_pluginv2_pallets_nominationPool.nominationPoolsInfoParams'
        description: params
        required: true
  /api/scan/nomination_pool/pool/member/vote:
    post:
      description: This API only supports networks with nominationPools frame
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {}
      summary: Nomination Pools Member Vote
      tags:
      - NominationPools
      x-synonyms:
      - nomination
      - pools
      - member
      - vote
      - nominationpools
      - scan
      - pool
      - staking pool
      - delegation
      - nomination pool
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_pluginv2_pallets_nominationPool.nominationPoolsMemberVoteParams'
        description: params
        required: true
  /api/scan/nomination_pool/pool/members:
    post:
      description: This API only supports networks with nominationPools frame
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {}
      summary: Nomination Pools Members
      tags:
      - NominationPools
      x-synonyms:
      - nomination
      - pools
      - members
      - nominationpools
      - scan
      - pool
      - staking pool
      - delegation
      - nomination pool
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_pluginv2_pallets_nominationPool.nominationPoolsMembersParams'
        description: params
        required: true
  /api/scan/nomination_pool/pools:
    post:
      description: This API only supports networks with nominationPools frame
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {}
      summary: Nomination Pools List
      tags:
      - NominationPools
      x-synonyms:
      - nomination
      - pools
      - nominationpools
      - scan
      - pool
      - staking pool
      - delegation
      - nomination pool
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_pluginv2_pallets_nominationPool.nominationPoolsListParams'
        description: params
        required: true
  /api/scan/nomination_pool/rewards:
    post:
      description: This API only supports networks with nominationPools frame
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {}
      summary: Nomination Pools Rewards
      tags:
      - NominationPools
      x-synonyms:
      - nomination
      - pools
      - rewards
      - nominationpools
      - scan
      - pool
      - staking pool
      - delegation
      - reward
      - payout
      - nomination pool
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_pluginv2_pallets_nominationPool.nominationPoolsRewardsParams'
        description: params
        required: true
components:
  schemas:
    internal_pluginv2_pallets_nominationPool.nominationPoolsListParams:
      properties:
        multi_state:
          items:
            type: string
          type: array
        state:
          enum:
          - Destroying
          - Open
          - Blocked
          - Destroyed
          type: string
      type: object
    internal_pluginv2_pallets_nominationPool.nominationPoolsMemberVoteParams:
      properties:
        address:
          type: string
      required:
      - address
      type: object
    internal_pluginv2_pallets_nominationPool.nominationPoolsMembersParams:
      properties:
        page:
          minimum: 0
          type: integer
        pool_id:
          type: integer
        row:
          maximum: 100
          minimum: 1
          type: integer
      required:
      - row
      type: object
    internal_pluginv2_pallets_nominationPool.nominationPoolsRewardsParams:
      properties:
        address:
          type: string
        page:
          minimum: 0
          type: integer
        pool_id:
          type: integer
        row:
          maximum: 100
          minimum: 1
          type: integer
      type: object
    internal_pluginv2_pallets_nominationPool.nominationPoolsInfoParams:
      properties:
        pool_id:
          type: integer
      type: object
    internal_pluginv2_pallets_nominationPool.nominationPoolsActivitiesParams:
      properties:
        page:
          minimum: 0
          type: integer
        pool_id:
          type: integer
        row:
          maximum: 100
          minimum: 1
          type: integer
      type: object
