openapi: 3.2.0
info:
  contact:
    email: bruce.sun@itering.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a subscan API server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Subscan Enjin API
  version: '1.0'
servers:
- url: https://https://www.subscan.io/
tags:
- name: Enjin
paths:
  /api/scan/multiTokens/account/balances:
    post:
      description: This API is only available for enjin/matrix network.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subscan_internal_plugin_share.J'
      summary: Enjin multiToken holder balance
      tags:
      - Enjin
      x-synonyms:
      - enjin
      - multitoken
      - holder
      - balance
      - scan
      - multitokens
      - account
      - balances
      - owner
      - balance holder
      - wallet
      - address
      - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_plugin_enjin_multiTokens_http.EnjinMultiTokenHolderBalanceParams'
        description: params
        required: true
  /api/scan/multiTokens/activities:
    post:
      description: This API is only available for enjin/matrix network.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subscan_internal_plugin_share.J'
      summary: Enjin multiToken activities
      tags:
      - Enjin
      x-synonyms:
      - enjin
      - multitoken
      - activities
      - scan
      - multitokens
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_plugin_enjin_multiTokens_http.EnjinMultiTokenActivitiesParams'
        description: params
        required: true
  /api/scan/multiTokens/holders:
    post:
      description: This API is only available for enjin/matrix network.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subscan_internal_plugin_share.J'
      summary: Enjin multiToken holders
      tags:
      - Enjin
      x-synonyms:
      - enjin
      - multitoken
      - holders
      - scan
      - multitokens
      - owners
      - token holders
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_plugin_enjin_multiTokens_http.EnjinMultiTokenHoldersParams'
        description: params
        required: true
  /api/scan/multiTokens/info:
    post:
      description: This API is only available for enjin/matrix network.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subscan_internal_plugin_share.J'
      summary: Enjin multiToken info
      tags:
      - Enjin
      x-synonyms:
      - enjin
      - multitoken
      - scan
      - multitokens
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_plugin_enjin_multiTokens_http.EnjinMultiTokeInfoParams'
        description: params
        required: true
  /api/scan/multiTokens/info/item:
    post:
      description: This API is only available for enjin/matrix network.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subscan_internal_plugin_share.J'
      summary: Enjin multiToken item detail
      tags:
      - Enjin
      x-synonyms:
      - enjin
      - multitoken
      - item
      - scan
      - multitokens
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_plugin_enjin_multiTokens_http.EnjinMultiTokenItemParams'
        description: params
        required: true
  /api/scan/multiTokens/items:
    post:
      description: This API is only available for enjin/matrix network.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subscan_internal_plugin_share.J'
      summary: Enjin multiToken item all
      tags:
      - Enjin
      x-synonyms:
      - enjin
      - multitoken
      - item
      - scan
      - multitokens
      - items
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_plugin_enjin_multiTokens_http.EnjinMultiTokenItemsParams'
        description: params
        required: true
  /api/scan/multiTokens/list:
    post:
      description: This API is only available for enjin/matrix network.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subscan_internal_plugin_share.J'
      summary: Enjin multiToken list
      tags:
      - Enjin
      x-synonyms:
      - enjin
      - multitoken
      - scan
      - multitokens
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_plugin_enjin_multiTokens_http.EnjinMultiTokenParams'
        description: params
        required: true
components:
  schemas:
    internal_plugin_enjin_multiTokens_http.EnjinMultiTokenActivitiesParams:
      properties:
        collection_id:
          description: multiToken collection id
          type: string
        page:
          minimum: 0
          type: integer
        row:
          maximum: 100
          minimum: 1
          type: integer
        token_id:
          description: Optional. filter by token id
          type: string
      type: object
    internal_plugin_enjin_multiTokens_http.EnjinMultiTokenHoldersParams:
      properties:
        collection_id:
          description: multiToken collection id
          type: string
        page:
          minimum: 0
          type: integer
        row:
          maximum: 100
          minimum: 1
          type: integer
        token_id:
          description: optional. filter by token id
          type: string
      required:
      - collection_id
      type: object
    internal_plugin_enjin_multiTokens_http.EnjinMultiTokenParams:
      properties:
        collection_id:
          description: Optional, multiToken collection id
          type: string
        order:
          description: Optional, order sort, default desc
          enum:
          - desc
          - asc
          type: string
        order_field:
          description: Optional, order field
          enum:
          - items
          - holders
          - collection_id
          - transfer_count
          type: string
        page:
          minimum: 0
          type: integer
        row:
          maximum: 100
          minimum: 1
          type: integer
        search:
          description: Optional, multiToken collection name
          maxLength: 256
          minLength: 1
          type: string
      type: object
    subscan_internal_plugin_share.J:
      properties:
        code:
          example: 0
          type: integer
        data: {}
        generated_at:
          example: 1699600641
          type: integer
        message:
          example: Success
          type: string
      type: object
    internal_plugin_enjin_multiTokens_http.EnjinMultiTokenItemParams:
      properties:
        collection_id:
          type: string
        token_id:
          type: string
      type: object
    internal_plugin_enjin_multiTokens_http.EnjinMultiTokenItemsParams:
      properties:
        collection_id:
          description: Optional. multiToken collection id
          type: string
        order:
          description: Optional, order sort, default desc
          enum:
          - desc
          - asc
          type: string
        order_field:
          description: Optional, order field
          enum:
          - holders
          - item_id
          - create_at
          - transfer_count
          type: string
        page:
          minimum: 0
          type: integer
        row:
          description: Owner        string           `json:"owner" binding:"omitempty,addr"`           // Optional. multiToken owner address. Only support ss58 address
          maximum: 100
          minimum: 1
          type: integer
      type: object
    internal_plugin_enjin_multiTokens_http.EnjinMultiTokeInfoParams:
      properties:
        collection_id:
          description: multiToken collection id
          type: string
      type: object
    internal_plugin_enjin_multiTokens_http.EnjinMultiTokenHolderBalanceParams:
      properties:
        address:
          type: string
        collection_id:
          type: string
        page:
          minimum: 0
          type: integer
        row:
          maximum: 100
          minimum: 1
          type: integer
      required:
      - address
      type: object
