openapi: 3.2.0
info:
  contact:
    email: bruce.sun@itering.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a subscan API server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Subscan Avail API
  version: '1.0'
servers:
- url: https://https://www.subscan.io/
tags:
- name: Avail
paths:
  /api/scan/dataAvailability/info:
    post:
      description: This API is only available for avail network.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
      summary: Submitted Data info
      tags:
      - Avail
      x-synonyms:
      - submitted
      - data
      - avail
      - scan
      - dataavailability
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_plugin_avail_dataAvailability_http.SubmittedDataInfoParam'
        description: param
        required: true
  /api/scan/dataAvailability/list:
    post:
      description: This API is only available for avail network.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/subscan_internal_plugin_share.J'
                - properties:
                    data:
                      properties:
                        count:
                          type: integer
                        list:
                          items:
                            $ref: '#/components/schemas/subscan_internal_plugin_avail_dataAvailability_db.AppDataJson'
                          type: array
                        size:
                          type: integer
                      type: object
                  type: object
      summary: Submitted Data list
      tags:
      - Avail
      x-synonyms:
      - submitted
      - data
      - avail
      - scan
      - dataavailability
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_plugin_avail_dataAvailability_http.SubmittedListParam'
        description: param
        required: true
  /api/scan/vector/daily:
    post:
      description: This API only available for avail network.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/subscan_internal_plugin_share.J'
                - properties:
                    data:
                      items:
                        $ref: '#/components/schemas/subscan_internal_plugin_avail_vector_db.VectorTransferDailyJson'
                      type: array
                  type: object
      summary: vector transfer daily list
      tags:
      - Avail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_plugin_avail_vector_http.transferDailyParam'
        description: param
        required: true
  /api/scan/vector/statistics:
    post:
      description: This API only available for avail network.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/subscan_internal_plugin_share.J'
                - properties:
                    data:
                      $ref: '#/components/schemas/subscan_internal_plugin_avail_vector_db.VectorTransferStatistics'
                  type: object
      summary: Transfer count statistics
      tags:
      - Avail
  /api/scan/vector/transfer:
    post:
      description: This API only available for avail network.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/subscan_internal_plugin_share.J'
                - properties:
                    data:
                      properties:
                        count:
                          type: integer
                        list:
                          items:
                            $ref: '#/components/schemas/subscan_internal_plugin_avail_vector_db.VectorTransferJson'
                          type: array
                      type: object
                  type: object
      summary: vector transfer list
      tags:
      - Avail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_plugin_avail_vector_http.transferParam'
        description: param
        required: true
components:
  schemas:
    subscan_internal_plugin_avail_vector_db.VectorTransferJson:
      properties:
        amount:
          type: string
        block_num:
          type: integer
        block_timestamp:
          type: integer
        extrinsic_index:
          type: string
        id:
          type: integer
        receiver:
          $ref: '#/components/schemas/subscan_internal_model.AccountDisplay'
        result:
          type: boolean
        sender:
          $ref: '#/components/schemas/subscan_internal_model.AccountDisplay'
        token_id:
          type: string
      type: object
    internal_plugin_avail_vector_http.transferDailyParam:
      properties:
        end:
          example: '2023-06-01'
          type: string
        format:
          enum:
          - day
          - week
          - month
          example: day
          type: string
        start:
          example: '2023-05-01'
          type: string
      required:
      - end
      - start
      type: object
    internal_plugin_avail_vector_http.transferParam:
      properties:
        address:
          type: string
        block_range:
          type: string
        max_amount:
          type: string
        min_amount:
          type: string
        page:
          minimum: 0
          type: integer
        receiver:
          type: string
        result:
          type: boolean
        row:
          maximum: 100
          minimum: 1
          type: integer
        sender:
          type: string
      type: object
    subscan_internal_model.SampleIdentity:
      properties:
        display:
          type: string
        identity:
          type: boolean
        judgements:
          items:
            $ref: '#/components/schemas/subscan_internal_model.RegistrationJudgementJson'
          type: array
        parent:
          $ref: '#/components/schemas/subscan_internal_model.AccountParentJson'
      type: object
    subscan_internal_model.AccountParentJson:
      properties:
        address:
          type: string
        display:
          type: string
        identity:
          type: boolean
        sub_symbol:
          type: string
      type: object
    subscan_internal_model.EvmAccountDisplay:
      properties:
        contract_name:
          type: string
        verify_source:
          type: string
      type: object
    subscan_internal_plugin_avail_vector_db.VectorTransferStatistics:
      properties:
        avail_to_eth_count:
          type: integer
        avail_to_eth_sum:
          type: string
        eth_to_avail_count:
          type: integer
        eth_to_avail_sum:
          type: string
      type: object
    subscan_internal_plugin_share.J:
      properties:
        code:
          example: 0
          type: integer
        data: {}
        generated_at:
          example: 1699600641
          type: integer
        message:
          example: Success
          type: string
      type: object
    subscan_internal_plugin_avail_vector_db.VectorTransferDailyJson:
      properties:
        avail_to_eth_count:
          type: integer
        avail_to_eth_sum:
          type: string
        date:
          type: string
        eth_to_avail_count:
          type: integer
        eth_to_avail_sum:
          type: string
      type: object
    internal_plugin_avail_dataAvailability_http.SubmittedListParam:
      properties:
        address:
          type: string
        app_id:
          type: integer
        block_num:
          minimum: 1
          type: integer
        extrinsic_index:
          type: string
        page:
          minimum: 0
          type: integer
        row:
          maximum: 100
          minimum: 1
          type: integer
      type: object
    internal_plugin_avail_dataAvailability_http.SubmittedDataInfoParam:
      properties:
        extrinsic_index:
          example: 277764-458
          type: string
        hash:
          example: 19113970726987136144018792964335985025967463666252479637084635182152021787304
          type: string
      required:
      - extrinsic_index
      - hash
      type: object
    subscan_internal_model.AccountDisplay:
      properties:
        account_index:
          type: string
        address:
          description: Current network account
          type: string
        display:
          type: string
        evm_address:
          type: string
        evm_contract:
          $ref: '#/components/schemas/subscan_internal_model.EvmAccountDisplay'
        identity:
          type: boolean
        judgements:
          items:
            $ref: '#/components/schemas/subscan_internal_model.RegistrationJudgementJson'
          type: array
        merkle:
          $ref: '#/components/schemas/subscan_internal_model.MerkleTag'
        parent:
          allOf:
          - $ref: '#/components/schemas/subscan_internal_model.AccountParentJson'
          description: Parent account
        people:
          $ref: '#/components/schemas/subscan_internal_model.SampleIdentity'
      type: object
    subscan_internal_plugin_avail_dataAvailability_db.AppDataJson:
      properties:
        account:
          $ref: '#/components/schemas/subscan_internal_model.AccountDisplay'
        app_id:
          type: integer
        data_hash:
          type: string
        extrinsic_index:
          type: string
        size:
          type: integer
      type: object
    subscan_internal_model.MerkleTag:
      properties:
        address_type:
          type: string
        tag_name:
          type: string
        tag_subtype:
          type: string
        tag_type:
          type: string
      type: object
    subscan_internal_model.RegistrationJudgementJson:
      properties:
        index:
          type: integer
        judgement:
          type: string
      type: object
