openapi: 3.2.0
info:
  contact:
    email: bruce.sun@itering.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a subscan API server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Subscan Metadata API
  version: '1.0'
servers:
- url: https://https://www.subscan.io/
tags:
- name: Metadata
paths:
  /api/scan/metadata:
    post:
      description: Current network metadata, including current networkNode name, ss58 addressType and other information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/internal_server_http.J'
                - properties:
                    data:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
      summary: Current network metadata
      tags:
      - Metadata
      x-synonyms:
      - current
      - network
      - metadata
      - scan
      - meta
      - chain info
components:
  schemas:
    internal_server_http.J:
      properties:
        code:
          example: 0
          type: integer
        data: {}
        generated_at:
          example: 1699600641
          type: integer
        message:
          example: Success
          type: string
      type: object
