openapi: 3.2.0
info:
  contact:
    email: bruce.sun@itering.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a subscan API server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Subscan Moonbeam API
  version: '1.0'
servers:
- url: https://https://www.subscan.io/
tags:
- name: Moonbeam
paths:
  /api/scan/orbiters/rewards:
    post:
      description: This API is only available for moonbeam(moonriver,moonbase) network.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/subscan_internal_plugin_share.J'
                - properties:
                    data:
                      properties:
                        count:
                          type: integer
                        list:
                          items:
                            $ref: '#/components/schemas/internal_pluginv2_customizeds_moonbeam_orbiters.OrbiterReward'
                          type: array
                      type: object
                  type: object
      summary: Get Moonbeam Orbiters rewards
      tags:
      - Moonbeam
      x-synonyms:
      - moonbeam
      - orbiters
      - rewards
      - scan
      - reward
      - payout
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_pluginv2_customizeds_moonbeam_orbiters.OrbitersRewardParams'
        description: param
        required: true
components:
  schemas:
    internal_pluginv2_customizeds_moonbeam_orbiters.OrbiterReward:
      properties:
        amount:
          type: string
        block_timestamp:
          type: integer
        event_id:
          type: string
        event_index:
          type: string
        extrinsic_index:
          type: string
        module_id:
          type: string
      type: object
    internal_pluginv2_customizeds_moonbeam_orbiters.OrbitersRewardParams:
      properties:
        address:
          type: string
        page:
          minimum: 0
          type: integer
        row:
          maximum: 100
          minimum: 1
          type: integer
      type: object
    subscan_internal_plugin_share.J:
      properties:
        code:
          example: 0
          type: integer
        data: {}
        generated_at:
          example: 1699600641
          type: integer
        message:
          example: Success
          type: string
      type: object
